server:
  port: 8080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?stringtype=unspecified
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org: info
